apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
  name: collectd-exporter-http
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9103
    targetPort: 9103
  selector:
    app: collectd-exporter
  type: LoadBalancer
