apiVersion: v1
kind: Service
metadata:
  name: collectd-exporter
  namespace: monitoring
spec:
  ports:
  - name: collectd
    port: 25826
    protocol: UDP
    targetPort: 25826
  selector:
    app: collectd-exporter
  type: NodePort
