apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: intranet
  name: collectd-exporter
  namespace: monitoring
spec:
  ports:
  - name: collectd
    port: 25826
    protocol: UDP
    targetPort: 25826
  selector:
    app: collectd-exporter
  type: LoadBalancer
