apiVersion: v1
kind: Service
metadata:
  annotations:
UPDATE-ME
  name: grafana
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: grafana
  type: LoadBalancer
