apiVersion: v1
kind: Service
metadata:
  annotations:
      cloud.google.com/load-balancer-type: Internal
  labels:
    prometheus: k8s
  name: prometheus-k8s
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
    app: prometheus
    prometheus: k8s
  type: LoadBalancer
